#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;

define('BASE_PATH', __DIR__);

$app = new App(
    config: [
        'app_path' => __DIR__ . '/src/Console/Commands',
        'debug' => false,
    ]
);
$app->setSignature('fox ...');

$app->runCommand($argv);
