<?php

declare(strict_types=1);

return [
    [
        'method' => 'get',
        'route' => '/accounts',
        'name' => 'listAccountsForUser',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/accounts',
        'name' => 'createAccount',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/accounts/types',
        'name' => 'listAccountTypesForUser',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'delete',
        'route' => '/accounts/{account_id}',
        'name' => 'cancelAccount',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/accounts/{account_id}',
        'name' => 'getAccount',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/accounts/{account_id}',
        'name' => 'updateAccount',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/accounts/{account_id}/audit',
        'name' => 'listAccountAuditEvents',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/billing/payment_methods',
        'name' => 'listPaymentMethodsForUser',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/builds/{build_id}',
        'name' => 'getSiteBuild',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/builds/{build_id}/log',
        'name' => 'updateSiteBuildLog',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/builds/{build_id}/start',
        'name' => 'notifyBuildStart',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/deploy_keys',
        'name' => 'listDeployKeys',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/deploy_keys',
        'name' => 'createDeployKey',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'delete',
        'route' => '/deploy_keys/{key_id}',
        'name' => 'deleteDeployKey',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/deploy_keys/{key_id}',
        'name' => 'getDeployKey',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/deploys/{deploy_id}',
        'name' => 'getDeploy',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/deploys/{deploy_id}/cancel',
        'name' => 'cancelSiteDeploy',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/deploys/{deploy_id}/files/{path}',
        'name' => 'uploadDeployFile',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/deploys/{deploy_id}/functions/{name}',
        'name' => 'uploadDeployFunction',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/deploys/{deploy_id}/lock',
        'name' => 'lockDeploy',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/deploys/{deploy_id}/plugin_runs',
        'name' => 'createPluginRun',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/deploys/{deploy_id}/unlock',
        'name' => 'unlockDeploy',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/dns_zones',
        'name' => 'getDnsZones',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/dns_zones',
        'name' => 'createDnsZone',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'delete',
        'route' => '/dns_zones/{zone_id}',
        'name' => 'deleteDnsZone',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/dns_zones/{zone_id}',
        'name' => 'getDnsZone',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/dns_zones/{zone_id}/dns_records',
        'name' => 'getDnsRecords',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/dns_zones/{zone_id}/dns_records',
        'name' => 'createDnsRecord',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'delete',
        'route' => '/dns_zones/{zone_id}/dns_records/{dns_record_id}',
        'name' => 'deleteDnsRecord',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/dns_zones/{zone_id}/dns_records/{dns_record_id}',
        'name' => 'getIndividualDnsRecord',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/dns_zones/{zone_id}/transfer',
        'name' => 'transferDnsZone',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/forms/{form_id}/submissions',
        'name' => 'listFormSubmissions',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/hooks',
        'name' => 'listHooksBySiteId',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/hooks',
        'name' => 'createHookBySiteId',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/hooks/types',
        'name' => 'listHookTypes',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'delete',
        'route' => '/hooks/{hook_id}',
        'name' => 'deleteHook',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/hooks/{hook_id}',
        'name' => 'getHook',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/hooks/{hook_id}',
        'name' => 'updateHook',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/hooks/{hook_id}/enable',
        'name' => 'enableHook',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/oauth/tickets',
        'name' => 'createTicket',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/oauth/tickets/{ticket_id}',
        'name' => 'showTicket',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/oauth/tickets/{ticket_id}/exchange',
        'name' => 'exchangeTicket',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/services/',
        'name' => 'getServices',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/services/{addonName}',
        'name' => 'showService',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/services/{addonName}/manifest',
        'name' => 'showServiceManifest',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites',
        'name' => 'listSites',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/sites',
        'name' => 'createSite',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'delete',
        'route' => '/sites/{site_id}',
        'name' => 'deleteSite',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}',
        'name' => 'getSite',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'patch',
        'route' => '/sites/{site_id}',
        'name' => 'updateSite',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/assets',
        'name' => 'listSiteAssets',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/sites/{site_id}/assets',
        'name' => 'createSiteAsset',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'delete',
        'route' => '/sites/{site_id}/assets/{asset_id}',
        'name' => 'deleteSiteAsset',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/assets/{asset_id}',
        'name' => 'getSiteAssetInfo',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/sites/{site_id}/assets/{asset_id}',
        'name' => 'updateSiteAsset',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/assets/{asset_id}/public_signature',
        'name' => 'getSiteAssetPublicSignature',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/build_hooks',
        'name' => 'listSiteBuildHooks',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/sites/{site_id}/build_hooks',
        'name' => 'createSiteBuildHook',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'delete',
        'route' => '/sites/{site_id}/build_hooks/{id}',
        'name' => 'deleteSiteBuildHook',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/build_hooks/{id}',
        'name' => 'getSiteBuildHook',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/sites/{site_id}/build_hooks/{id}',
        'name' => 'updateSiteBuildHook',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/builds',
        'name' => 'listSiteBuilds',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/sites/{site_id}/builds',
        'name' => 'createSiteBuild',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/deployed-branches',
        'name' => 'listSiteDeployedBranches',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/deploys',
        'name' => 'listSiteDeploys',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/sites/{site_id}/deploys',
        'name' => 'createSiteDeploy',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/deploys/{deploy_id}',
        'name' => 'getSiteDeploy',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/sites/{site_id}/deploys/{deploy_id}',
        'name' => 'updateSiteDeploy',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/sites/{site_id}/deploys/{deploy_id}/restore',
        'name' => 'restoreSiteDeploy',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/dns',
        'name' => 'getDNSForSite',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/sites/{site_id}/dns',
        'name' => 'configureDNSForSite',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/files',
        'name' => 'listSiteFiles',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/files/{file_path}',
        'name' => 'getSiteFileByPathName',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/forms',
        'name' => 'listSiteForms',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'delete',
        'route' => '/sites/{site_id}/forms/{form_id}',
        'name' => 'deleteSiteForm',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/metadata',
        'name' => 'getSiteMetadata',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/sites/{site_id}/metadata',
        'name' => 'updateSiteMetadata',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/plugin_runs/latest',
        'name' => 'getLatestPluginRuns',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/sites/{site_id}/plugins/{package}',
        'name' => 'updatePlugin',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/sites/{site_id}/rollback',
        'name' => 'rollbackSiteDeploy',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/service-instances',
        'name' => 'listServiceInstancesForSite',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/sites/{site_id}/services/{addon}/instances',
        'name' => 'createServiceInstance',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'delete',
        'route' => '/sites/{site_id}/services/{addon}/instances/{instance_id}',
        'name' => 'deleteServiceInstance',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/services/{addon}/instances/{instance_id}',
        'name' => 'showServiceInstance',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/sites/{site_id}/services/{addon}/instances/{instance_id}',
        'name' => 'updateServiceInstance',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/snippets',
        'name' => 'listSiteSnippets',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/sites/{site_id}/snippets',
        'name' => 'createSiteSnippet',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'delete',
        'route' => '/sites/{site_id}/snippets/{snippet_id}',
        'name' => 'deleteSiteSnippet',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/snippets/{snippet_id}',
        'name' => 'getSiteSnippet',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/sites/{site_id}/snippets/{snippet_id}',
        'name' => 'updateSiteSnippet',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/ssl',
        'name' => 'showSiteTLSCertificate',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/sites/{site_id}/ssl',
        'name' => 'provisionSiteTLSCertificate',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/submissions',
        'name' => 'listSiteSubmissions',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/traffic_splits',
        'name' => 'getSplitTests',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/sites/{site_id}/traffic_splits',
        'name' => 'createSplitTest',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/sites/{site_id}/traffic_splits/{split_test_id}',
        'name' => 'getSplitTest',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/sites/{site_id}/traffic_splits/{split_test_id}',
        'name' => 'updateSplitTest',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/sites/{site_id}/traffic_splits/{split_test_id}/publish',
        'name' => 'enableSplitTest',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/sites/{site_id}/traffic_splits/{split_test_id}/unpublish',
        'name' => 'disableSplitTest',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'put',
        'route' => '/sites/{site_id}/unlink_repo',
        'name' => 'unlinkSiteRepo',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'delete',
        'route' => '/submissions/{submission_id}',
        'name' => 'deleteSubmission',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/submissions/{submission_id}',
        'name' => 'listFormSubmission',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/user',
        'name' => 'getCurrentUser',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/{account_id}/builds/status',
        'name' => 'getAccountBuildStatus',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/{account_slug}/members',
        'name' => 'listMembersForAccount',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/{account_slug}/members',
        'name' => 'addMemberToAccount',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/{account_slug}/sites',
        'name' => 'listSitesForAccount',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'post',
        'route' => '/{account_slug}/sites',
        'name' => 'createSiteInTeam',
        'handler' => '',
        'middleware' => [],
    ],
    [
        'method' => 'get',
        'route' => '/accounts/{account_id}/audit',
        'name' => 'listAccountAuditEvents',
        'handler' => 'some class',
        'middleware' => [],
    ],
];
